### ISSUE TITLE
Make Plane Alert External Link Configurable

### ISSUE THREAD

**Issue by Phaeton** [sdr-enthusiasts/docker-planefence#172]
@kx1t It would be nice to make the Plane Alert link configurable between the various aggregator services.

**Comment by dziban303** [comment]
I was tempted to work on this this morning. I saw the bit of the config file parsing talking about it, I guess it was never implemented though some of the groundwork is already complete. Easy mode is just `sed`ing in your site of choice.

**Comment by kx1t** [comment]
we implemented this a while ago... closing
