### ISSUE TITLE
change function of $ and # in headers

### ISSUE THREAD

**Issue by Sportsbadger** [sdr-enthusiasts/docker-planefence#92]
It seems logical to have # control tweeting behaviour and $ to control rendering behaviour. The current implementation is counter-intuitive.

**Comment by kx1t** [comment]
The history behind the current implementation is that `#` means "comment"
in most programming languages. When we added the hashtag functionality, we
needed a different character to distinguish.
Another consideration is that changing this creates an impact on already
fielded instances of Planefence and Plane-Alert. My goal is to provide as
much backward compatibility as possible, with existing set-ups working
perfectly fine even when new features come on-line.

Therefore I'd like to think this one through a bit longer - I definitely
agree that "#" for hashtags is the most logical choice, but I want to
consider the impact of making this change before committing.
